#!/bin/bash
# Setup Obsidian vault structure and templates
# Usage: ./setup-vault.sh [vault-path]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEB_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

VAULT_PATH="${1:-$(cd "$WEB_DIR/../.." && pwd)/memoryan}"

echo "Setting up vault at: $VAULT_PATH"

# Create directory structure
mkdir -p "$VAULT_PATH/.obsidian/plugins"
mkdir -p "$VAULT_PATH/PAAP Memory/Providers"
mkdir -p "$VAULT_PATH/PAAP Memory/Models"
mkdir -p "$VAULT_PATH/PAAP Memory/MCP"
mkdir -p "$VAULT_PATH/PAAP Memory/Config"
mkdir -p "$VAULT_PATH/PAAP Memory/Logs"

# Create app.json
cat > "$VAULT_PATH/.obsidian/app.json" << 'EOF'
{
  "showLineNumber": true,
  "strictLineBreaks": false,
  "readableLineLength": true
}
EOF

# Create PAAP Memory index
cat > "$VAULT_PATH/PAAP Memory/README.md" << 'EOF'
# PAAP Memory

This folder contains memory snapshots from the PAAP (Pluggable AI API Proxy) system.

## Structure

- `Providers/` - Provider configurations and key information
- `Models/` - Available models and their capabilities
- `MCP/` - MCP server configuration and tools
- `Config/` - System configuration snapshots
- `Logs/` - Recent activity logs

## Integration

This vault is connected to PAAP via MCP bridge. The AI assistant can:
- Read existing notes for context
- Write new memory entries
- Update provider information
- Log system events

## Usage

1. Open this vault in Obsidian
2. The PAAP system will automatically sync relevant data
3. Use the graph view to explore relationships between providers and models
EOF

# Create welcome note
cat > "$VAULT_PATH/Welcome.md" << 'EOF'
# Welcome to PAAP Memory Vault

This vault is integrated with your PAAP (Pluggable AI API Proxy) system.

## Features

- **Auto-sync**: Provider configurations are automatically captured
- **Context bridge**: The AI assistant can read your notes for better assistance
- **Graph view**: Visualize relationships between providers, models, and configurations

## Getting Started

1. Explore the `PAAP Memory/` folder for system snapshots
2. Add your own notes alongside the auto-generated content
3. Use Obsidian's graph view to see connections

---

*Generated by PAAP setup script*
EOF

echo "✓ Vault structure created"
echo "✓ Obsidian config files generated"
echo "✓ Memory templates created"
echo ""
echo "Next steps:"
echo "1. Open Obsidian and select '$VAULT_PATH' as your vault"
echo "2. Enable the MCP bridge plugin if not already enabled"
echo "3. The PAAP system will start syncing data automatically"
